#!/bin/sh
sleep 10s
if [ -x "$(command -v opkg)" ]; then
    PACKAGE_MANAGER="opkg list-installed"
    echo "opkg package manager detected." [cite: 1] >&2
elif [ -x "$(command -v apk)" ];
then
    PACKAGE_MANAGER="apk list --installed"
    echo "apk package manager detected." [cite: 2] >&2
else
    echo "No supported package manager (opkg, apk) found."  >&2
    exit 1
fi
until [ "$( $PACKAGE_MANAGER 2>/dev/null| grep -c "^kernel")" -ne '0' ]; [cite: 4]
do
  sleep 1
done
chmod +x /usr/share/extpart.sh
ln -s /usr/share/extpart.sh /bin/extpart
fi
uci set luci.main.mediaurlbase='/luci-static/bootstrap'
uci commit luci

sed -i "s/option rollback '60'/option rollback '30'/" /etc/config/luci
sed -i "s/option holdoff '4'/option holdoff '2'/" /etc/config/luci
sed -i "s/option timeout '5'/option timeout '3'/" /etc/config/luci
sed -i "s/option display '1.5'/option display '1'/" /etc/config/luci

if [ "$( $PACKAGE_MANAGER 2>/dev/null|
grep -c "^luci-app-fancontrol")" -ne '0' ] && [ "$(grep -c "AXT1800" /etc/board.json)" -ne '0' ];then
  uci set fancontrol.settings.enabled='1'
  uci set fancontrol.settings.fan_file='/sys/devices/virtual/thermal/cooling_device1/cur_state'
  uci set fancontrol.settings.start_speed='65'
  uci set fancontrol.settings.start_temp='70'
  uci commit fancontrol
  /etc/init.d/fancontrol restart
  echo "0 20 * * * uci set fancontrol.settings.start_temp='75' && uci commit fancontrol && /etc/init.d/fancontrol restart" >> [cite: 6] /etc/crontabs/root
  echo "30 9 * * * uci set fancontrol.settings.start_temp='65' && uci commit fancontrol && /etc/init.d/fancontrol restart" >> /etc/crontabs/root
fi

uci commit

#if [ "$(grep -c "net.netfilter.nf_conntrack_max=65535" /etc/sysctl.conf)" -eq '0' ];then
#  echo "net.netfilter.nf_conntrack_max=65535" >> /etc/sysctl.conf
#  /etc/init.d/network restart
#fi
if [ "$( $PACKAGE_MANAGER 2>/dev/null|
grep -c "turboacc")" [cite: 7] 
-ne '0' ] && [ "$(grep -c "AXT1800" /etc/board.json)" -ne '0' ];then
  uci set turboacc.config.fullcone_nat6='0'
  uci set turboacc.config.bbr_cca='0'
  uci set turboacc.config.sw_flow='0'
  /etc/init.d/turboacc restart
fi

if [ "$( $PACKAGE_MANAGER 2>/dev/null|
grep -c "ramfree")" -ne '0' ] && [ "$(grep -c "/proc/sys/vm/drop_caches" /etc/crontabs/root)" -eq '0' ];then
  echo "0 */1 * * * sync && echo 3 > /proc/sys/vm/drop_caches" >> /etc/crontabs/root
fi

if [ -e /sys/class/leds/white:system/brightness ] && [ "$(grep -c "30 23 * * * echo "0" > /sys/class/leds/white:system/brightness" /etc/crontabs/root)" -eq '0' ];then
  echo "30 23 * * * echo 0 > /sys/class/leds/white:system/brightness" >> /etc/crontabs/root
fi

if [ -e /sys/class/leds/white:system/brightness 
[cite: 8] ] && [ "$(grep -c "00 05 * * * echo "1" > /sys/class/leds/white:system/brightness" /etc/crontabs/root)" -eq '0' ];then
  echo "00 05 * * * echo 1 > /sys/class/leds/white:system/brightness" >> /etc/crontabs/root
fi

exit 0
